### ISSUE TITLE
Can we Collaborate? 

### ISSUE THREAD

**Issue by Muchai248** [Aeternalis-Ingenium/FastAPI-Backend-Template#15]

**Comment by furqanalishah** [comment]
Would you please elaborate?

**Comment by Aeternalis-Ingenium** [comment]
Hey there @Muchai248,

Everyone can create a pull request as long as it doesn't change the main goal of this repository 🚀

Having this said, I will close this Issue.

Thank you 🙏🏽

**Comment by Muchai248** [comment]
Okay
